### ISSUE TITLE
OOP Problem

### ISSUE THREAD

**Issue by denizyildizz** [BeraERKAYA/ceng396-software-engineering#1]
Houston, we have a problem! 
In the first iteration, we decided to use JavaScript while developing our web project but it is not an oop so, we have to look for new languages which is based on oop principles. I research node.js , Php based on Laravel framework and C# based on asp.net. Is there anybody have idea about these oop languages and their framework? Which one fits to our project?

**Comment by surguvec** [comment]
I knew node.js and C# from my previous internship. What is Laravel, I never hearh about it, I will search.

**Comment by denizyildizz** [comment]
Laravel is a web application framework with expressive, elegant syntax and it has large library which is useful for us I guess. It is free and accessible, providing powerful tools needed for large, robust applications.

**Comment by nisancandir** [comment]
I think we can use C# , because all of us familiar with this language and we used this in the Web Development class.

**Comment by denizyildizz** [comment]
C# is okey for me. If everyone okey with it I will change it, let me know about your thoughts.

**Comment by surguvec** [comment]
It is okey for me. Thank you to all.

**Comment by denizyildizz** [comment]
Okey, I updated it. Have a nice day :)
