### ISSUE TITLE
Task assign

### ISSUE THREAD

**Issue by denizyildizz** [BeraERKAYA/ceng396-software-engineering#3]
### In iteration 3 and 4 I made:
Usability 
Reliability
Performance
Supportability
Implementation
Glossary
Packaging
Legal
References from iteration 3
From iteration 4
 III. Definitions, acronyms, and abbreviations
IV. References
V. Overview
2. Current Software Architecture

### In iteration 3 and 4 Nisan made:
 I. Purpose of the system
II. Scope of the system
III. Objectives and success criteria of the project
II. Functional requirements
III. Non functional requirements
IV. System models (these are from ite.3)
 I. Purpose of the system (from now on from ite.4)
II. Design goals

So someone (Bera or Kevser) can make 
 *3. Proposed Software Architecture* and 
User interface—navigational paths and screen mock-ups and
 Interface sketch and add them to wiki page from iteration 4 until 11.55pm??

**Comment by BeraERKAYA** [comment]
**In iteration 3 and 4 I made:**

I created the all pages, and created pages layouts. 

**In iteration 3**, i did  **User interface—navigational paths and screen mock-ups** part. I created the tables and upload on the page.
